# FROM ubuntu

# RUN apt-get update
# RUN apt-get upgrade -y

# RUN apt-get install -y maven openjdk-17-jdk

FROM maven:3.9.9-eclipse-temurin-17

RUN mkdir /app
COPY src /app/src 
COPY pom.xml /app/pom.xml

# compile
WORKDIR /app
RUN mvn verify

CMD ["java", "-Xmx64m", "-Xms64m", "-jar", "target/words.jar"]